name: obilim
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #DI
  get_it: ^7.2.0

  # Value equality
  equatable: ^2.0.5

  # Functional programming thingies
  dartz: ^0.10.1
  path_provider: ^2.1.1
  
  #local data
  shared_preferences: ^2.0.17

  # Remote API
  http: ^1.1.0
  

  # navigation
  go_router: ^11.0.0

  #svg, icon, font
  #flutter_svg: 1.1.5
  #google_fonts: 5.1.0
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  #country_icons: ^2.0.2
  #fluttericon: ^2.0.0

  flutter_screenutil: ^5.9.0
  email_validator: ^2.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/png/illustrations/
    - assets/png/icons/
    - assets/png/icons/onboarding/
    - assets/png/icons/navbar/
    - assets/images/
    - assets/images/home_slider/
    - assets/images/onboarding/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
